default[:bamboo][:installpath] = "/opt/atlassian/bamboo"
default[:bamboo][:dir] = "/usr/local/bamboo"
default[:bamboo][:javahome] = "/usr/lib/jvm/jre"
default[:bamboo][:user] = "bamboo"
default[:bamboo][:update]=="no"